### ISSUE TITLE
Declaring vk*() symbols at global scope is illegal

### ISSUE THREAD

**Issue by HansKristian-ARM** [zeux/volk#1]
Had a look and saw that volkGenLoadDevice() is loading global symbols with vk*() namespace. As far as I've understood it, this is not allowed, and needs to be namespaced accordingly.

From spec:
```
On platforms where Vulkan is provided as a shared library, library symbols beginning with “vk”
and followed by a digit or uppercase letter are reserved for use by the implementation.
Applications which use Vulkan must not provide definitions of these symbols. This allows the
Vulkan shared library to be updated with additional symbols for new API versions or extensions
without causing symbol conflicts with existing applications.
```

There is some discussion around extension loading here, which might be relevant: https://github.com/KhronosGroup/Vulkan-Ecosystem/issues/21

**Comment by zeux** [comment]
In C++ this can be namespaced away but in C it can't. I can probably change this to use namespace volk + using namespace volk for C++, but this will make compilation awkward.

OTOH I don't see why this would be a problem, unless you link to libvulkan.so - which defeats the purpose of this library. Is there a practical case where this would break something?

**Comment by HansKristian-ARM** [comment]
I've had cases where the loader would find the symbols in the application rather than its own symbols creating infinite loops when calling certain things (something like LD_PRELOAD). It might be safe if dynamic visibility is forced to hidden or similar.

This happened even if you dlopen()-ed libvulkan.so and only used it for vkGetInstanceProcAddr.

**Comment by zeux** [comment]
Yeah - that's a good point. I was thinking of symbol visibility but forgot to actually do something about it. Pushed a change to fix it. I'll keep this issue open for a bit since I'd like to actually test this library on Linux :) (it works on Windows and Android).

**Comment by zeux** [comment]
This seems to work for Linux; I'll assume for the time being the practical problem is solved and that "library symbols" might refer to exported/visible symbols only and close this :)

**Comment by zeux** [comment]
FWIW one other issue I found when using volk is that the symbols defined by volk conflict with symbols defined by vulkan.h. This is not a problem if both are included in the same translation unit - volk.h will check that the usage is correct - but it *is* a problem if there's some translation unit that includes vulkan.h, which is potentially problematic. Now, it does mean that even if this usage was safe, the application would have to link to vulkan.dll/so which is not a great idea, but still it can be an issue.
