### ISSUE TITLE
Warnings from Volk with higher warnings enabled

### ISSUE THREAD

**Issue by GruelingPine185** [zeux/volk#130]
The same problem regarding other functions was previously addressed in #11. I'm new to Vulkan, Volk, and the whole graphics and rendering thing, so I'm not sure if this was intensional or not. Anyways, here is the relevant part from compiling Volk with `-std=c11 -O2 -Wall -Wextra -pedantic`. Oh, and this is using the `sdk-1.3.250` branch.

```sh
# ...
vendor/volk/volk.c:113:33: warning: a function declaration without a prototype is deprecated in all versions of C [-Wstrict-prototypes]
VkInstance volkGetLoadedInstance()
                                ^
                                 void
vendor/volk/volk.c:124:29: warning: a function declaration without a prototype is deprecated in all versions of C [-Wstrict-prototypes]
VkDevice volkGetLoadedDevice()
                            ^
                             void
2 warnings generated.
```

**Comment by zeux** [comment]
Thanks! This is now fixed in master.
