### ISSUE TITLE
Does device-optimized volk prevent using layers?

### ISSUE THREAD

**Issue by tobine** [zeux/volk#15]
Just a point of clarification after reading README. If using volk in the device-optimized manner to bypass loader dispatch table, does that mean that layer cannot be loaded?
So one usage model for volk would be to use it at the instance-level for development where platform loader and layers are still in use, then when ready to ship use the device-optimized setup?

**Comment by zeux** [comment]
No - layers work perfectly fine. volk doesn't bypass dispatch table, it uses GDPA to load device entrypoints. When debug layers are active, GDPA will go through debug layers. I should really clarify this in README...

**Comment by zeux** [comment]
Just in case, GDPA = GetDeviceProcAddr. I will edit README later today to clarify this point.

**Comment by tobine** [comment]
Great, thanks!
