### ISSUE TITLE
Question about adding as submodule

### ISSUE THREAD

**Issue by gruelingpine185** [zeux/volk#161]
Quick question, so I add volk to my projects like so:
```sh
git submodule add -b sdk-1.3.261 https://github.com/zeux/volk vendor/volk
```
. I try to use the "latest" version of volk available. Is there a way that I can use the releases (which by semver are more recent) instead of relying on the available branches? I'd prefer to use git to add it as opposed to downloading the zip.

Or am I doing this wrong? Should I just be adding whatever is in main (or master, or whatever it's called)?

**Comment by zeux** [comment]
If you want to always track latest version, I believe you need to use `-b master`.
