### ISSUE TITLE
Library naming conflict

### ISSUE THREAD

**Issue by jengelh** [zeux/volk#166]
vulkan-tools sdk-1.3.275 now requires volk to build. zeux/volk however collides with the existing GNU Radio libvolk:

* If we modify volk's CMakeLists.txt so build a SHARED library (static libraries are a no-go in Linux distros), libvolk.so is a point of collision

This makes it problematic to build a hypothetical software that (for whatever reason) wants to include both libvolk and volk. Considering gnuradio volk traces back to 2010 and zeux/volk only to 2018, please consider renaming.

**Comment by zeux** [comment]
This has been considered before; it’s 2024 now so renaming isn’t really feasible. It’s unfortunate but that concern seems to be restricted to Linux packaging, which isn’t how volk is predominantly used. Renaming won’t happen.

**Comment by jengelh** [comment]
This has little to do with Linux; it also happens with FreeBSD and no modifications to CMakeLists.txt.

```
# pkg install volk
[1/3] Fetching cpu_features-0.7.0.pkg: 100%   31 KiB  32.1kB/s    00:01    
[2/3] Fetching orc-0.4.34_1.pkg: 100%  274 KiB 280.2kB/s    00:01    
[3/3] Fetching volk-2.5.1.pkg: 100%  671 KiB 686.9kB/s    00:01    
Checking integrity... done (0 conflicting)
[1/3] Installing cpu_features-0.7.0...
[1/3] Extracting cpu_features-0.7.0: 100%
[2/3] Installing orc-0.4.34_1...
[2/3] Extracting orc-0.4.34_1: 100%
[3/3] Installing volk-2.5.1...
[3/3] Extracting volk-2.5.1: 100%
root@fbsd:/home/lx/volk # pkg list volk
...
/usr/local/lib/libvolk.so
/usr/local/lib/libvolk.so.2.5
/usr/local/lib/libvolk.so.2.5.1
root@fbsd:/home/lx/volk # make install
[100%] Built target volk
Install the project...
-- Install configuration: ""
-- Installing: /usr/local/include/volk.h
-- Installing: /usr/local/include/volk.c
-- Installing: /usr/local/lib/libvolk.a
-- Installing: /usr/local/lib/cmake/volk/volkTargets.cmake
-- Installing: /usr/local/lib/cmake/volk/volkTargets-noconfig.cmake
-- Installing: /usr/local/lib/cmake/volk/volkConfig.cmake
-- Installing: /usr/local/lib/cmake/volk/volkConfigVersion.cmake
root@fbsd:/home/lx/volk # ls -al /usr/local/lib/libvolk*
-rw-r--r--  1 root wheel  154688 Feb 27 12:27 /usr/local/lib/libvolk.a
lrwxr-xr-x  1 root wheel      14 Feb 16 07:17 /usr/local/lib/libvolk.so -> libvolk.so.2.5
lrwxr-xr-x  1 root wheel      16 Feb 16 07:17 /usr/local/lib/libvolk.so.2.5 -> libvolk.so.2.5.1
-rwxr-xr-x  1 root wheel 4468488 Feb 16 07:17 /usr/local/lib/libvolk.so.2.5.1
```

We now have two libvolk and it's totally ambiguous which one gets used when passing `-lvolk` to the linker (kind of depends on whether anything anywhere has added -Bstatic or -Bdynamic to the linker arguments).
