### ISSUE TITLE
volkLoadDevice(device) erases some function pointers

### ISSUE THREAD

**Issue by daniilvinn** [zeux/volk#173]
I ran into an issue when `volkLoadDevice(device)` can't load pointers of some functions, in my case - `vkCmdDrawMeshTasksEXT()`. The pointer gets loaded in `volkLoadInstance(instance)`, but for some reason it is set to nullptr on `volkLoadDevice(device)`. I'm using NVIDIA GTX 1660 Ti, I have VK_EXT_mesh_shader support and I'm using newest LunarG's SDK and newest NVIDIA's Game Ready driver.

**Comment by zeux** [comment]
Are you enabling VK_EXT_mesh_shader when creating the device?

**Comment by daniilvinn** [comment]
16xx series is Turing arch as well ass 2xxx series, so it supports mesh shading. I will check if I did everything you mentioned and write back.

**Comment by daniilvinn** [comment]
Yes, problem was indeed caused by me. I simply forgot to add it device extension list... I apologize for such inattention and thank you for quick response and help! I'm closing the issue.
