### ISSUE TITLE
does volk work with asan? 

### ISSUE THREAD

**Issue by nathants** [zeux/volk#181]
is it possible to use volk with asan? 

i've tried everything i can find to tweak asan around volk, but not matter what always fail here: 

```cpp
			res = vkCreateDevice(physicalDevice, &createInfo, nullptr, &device);
			assert(res == VK_SUCCESS);
```

with error:

```cpp
VK_EVENT_SET = 3,
```

do you use asan with volk? i'm running clang17, linux, glibc, with [wickedengine](https://github.com/turanszkij/WickedEngine).

thanks!

**Comment by zeux** [comment]
Should work fine, niagara (https://github.com/zeux/niagara/) works without issues with both AMD & NV GPUs on latest, using gcc / asan / ubuntu with glibc.

**Comment by nathants** [comment]
awesome! i will study that and see whats different about my setup.
