### ISSUE TITLE
Symbol `vkDeviceWaitIdle' causes overflow in R_X86_64_PC32 relocation

### ISSUE THREAD

**Issue by manhnt9** [zeux/volk#20]
I'm having these output, but the app still runs.
Is this important?
```
./ShadowMapping: Symbol `vkDeviceWaitIdle' causes overflow in R_X86_64_PC32 relocation
./ShadowMapping: Symbol `vkDeviceWaitIdle' causes overflow in R_X86_64_PC32 relocation
./ShadowMapping: Symbol `vkDestroySurfaceKHR' causes overflow in R_X86_64_PC32 relocation
./ShadowMapping: Symbol `vkDestroySurfaceKHR' causes overflow in R_X86_64_PC32 relocation
```

**Comment by zeux** [comment]
Interesting - I don't know off the top of my head what this indicates. What OS/compiler is this on? Is this a sample that I can try to build myself?

**Comment by zeux** [comment]
Closing this since no additional information is available; this is hopefully a build issue of some sort, e.g. trying to compile volk without -fPIC and linking it into a relocatable module.
