### ISSUE TITLE
why is volkLoadInstanceOnly not loading vkCreateWin32SurfaceKHR?

### ISSUE THREAD

**Issue by codethinki** [zeux/volk#208]
i call volkInitialize() successfully and then call vkLoadInstanceOnly but vkCreateWin32SurfaceKHR is still invalid, why?

thx for help in advance :)

**Comment by GamesTrap** [comment]
See https://github.com/zeux/volk?tab=readme-ov-file#building.

You need to define `VK_USE_PLATFORM_XXX_KHR` for your corresponding OS in the preprocessor to make platform-specific functions available.
So in your case you would have to define `VK_USE_PLATFORM_WIN32_KHR` to make `vkCreateWin32SurfaceKHR` usable.

**Comment by codethinki** [comment]
> See https://github.com/zeux/volk?tab=readme-ov-file#building.
> 
> You need to define `VK_USE_PLATFORM_XXX_KHR` for your corresponding OS in the preprocessor to make platform-specific functions available. So in your case you would have to define `VK_USE_PLATFORM_WIN32_KHR` to make `vkCreateWin32SurfaceKHR` usable.

i have VK_USE_PLATFORM_WIN32_KHR before the include in the pch and also did it in the preprocessor (bc the other define didn’t work) but nothing changed, still nullptr

**Comment by zeux** [comment]
Are you specifying the extension (VK_KHR_win32_surface) when creating the instance via ppEnabledExtensionNames/enabledExtensionCount?

**Comment by codethinki** [comment]
yes i do i have VK_KHR_win32_surface and VK_KHR_surface active

**Comment by codethinki** [comment]
i also discovered that it crashes when calling volkLoadInstance() ?? some read access violation

**Comment by codethinki** [comment]
I found the issue, turns out i dont know how libraries work. I just assumed that vcpkg would link a lib that contains the compiled volk.c but thats not the case and i just compiled without the volk.c file which apparently doesnt even create a compile time error. I now put it in my build system and everything works fine

sry for the inconvenience and thx for the amazing lib so i dont have to put up with those endless definitions and function loading :)
