### ISSUE TITLE
Change include of vulkan.h on windows platforms.

### ISSUE THREAD

**Issue by gabriellanzer** [zeux/volk#21]
**In order to avoid including windows.h with vulkan.h and subsequently with volk.h one thing to be done (as pointer by [Jérémie](https://twitter.com/batinsse/status/1147742418483187712)) is to include vk_platform.h and vulkan_core.h on the header:**
#ifndef VULKAN_H_
#if defined(_WIN32)
#include <vulkan/vk_platform.h>
#include <vulkan/vulkan_core.h>
#else
#include <vulkan/vulkan.h>
#endif
#endif

**Then, at the .c file use the following instead of #include <windows.h>:**
#ifdef _WIN32

typedef void* HANDLER;
typedef void* HINSTANCE;
typedef void* HWND;
typedef void* HMONITOR;
typedef void* HMODULE;
typedef const wchar_t* LPCWSTR;
typedef unsigned long DWORD;

typedef struct _SECURITY_ATTRIBUTES {
	DWORD nLength;
	void* lpSecurityDescriptor;
	int bInheritHandle;
} SECURITY_ATTRIBUTES;

typedef int64_t (__stdcall* FARPROC)(void);

void* __stdcall LoadLibraryA(const char* lpFileName);
FARPROC* __stdcall GetProcAddress(void* hModule, const char* lProcName);
void* __stdcall GetModuleHandleA(const char* lpModuleName);
void* __stdcall GetActiveWindow();

static void volkGenLoadLoader(void* context, PFN_vkVoidFunction (*load)(void*, const char*));
static void volkGenLoadInstance(void* context, PFN_vkVoidFunction (*load)(void*, const char*));
static void volkGenLoadDevice(void* context, PFN_vkVoidFunction (*load)(void*, const char*));
static void volkGenLoadDeviceTable(struct VolkDeviceTable* table, void* context, PFN_vkVoidFunction (*load)(void*, const char*));

static PFN_vkVoidFunction vkGetInstanceProcAddrStub(void* context, const char* name)
{
	return vkGetInstanceProcAddr((VkInstance)context, name);
}

static PFN_vkVoidFunction vkGetDeviceProcAddrStub(void* context, const char* name)
{
	return vkGetDeviceProcAddr((VkDevice)context, name);
}
#else
#include <dlfcn.h>
#endif

**Comment by gabriellanzer** [comment]
As an addition, since the Windows redefinitions must only be done in the .c file, there is no problem including windows.h further on the user's code.

**Comment by zeux** [comment]
Is the manual definition of LoadLibraryA etc. required in volk.c, or is the main goal to reduce the include cost of volk.h?

It looks like I can get this to work with both, but the amount of manual definitions in the header is slightly smaller than the full number of definitions required to compile volk.c.

**Comment by zeux** [comment]
Something like this seems to work in the header - I think this is more correct than the version proposed in the tweet.

```c++
#ifndef VULKAN_H_
#	ifdef VK_USE_PLATFORM_WIN32_KHR
#		include <vulkan/vk_platform.h>
#		include <vulkan/vulkan_core.h>

		typedef unsigned long DWORD;
		typedef const wchar_t* LPCWSTR;
		typedef void* HANDLE;
		typedef struct HINSTANCE__ *HINSTANCE;
		typedef struct HWND__* HWND;
		typedef struct HMONITOR__* HMONITOR;
		typedef struct _SECURITY_ATTRIBUTES SECURITY_ATTRIBUTES;

#		include <vulkan/vulkan_win32.h>
#	else
#		include <vulkan/vulkan.h>
#	endif
#endif
```

**Comment by gabriellanzer** [comment]
Nice! This solution looks better indeed.
