### ISSUE TITLE
platform macros and pre-built volk

### ISSUE THREAD

**Issue by jweg** [zeux/volk#29]
To get the platform-specific function pointers, one of the macros (e.g. VK_USE_PLATFORM_WIN32_KHR) must be set before including vulkan.h. However, those macros need to be defined at volk build time as well. I totally didn't think of that when I made the cmake package config and the vcpkg port.  Doesn't this mean that volk will in practice always have to be built as part of a user's project? Automatically setting the right define doesn't seem to be an option: it'd work for win32, but it couldn't make the choice between xcb, xlib, wayland, etc.
Am I missing something here? How did that work with the earlier simple CMakeLists? It didn't set any defines either.

**Comment by zeux** [comment]
> How did that work with the earlier simple CMakeLists? It didn't set any defines either.

As far as I know all CMake users defined VK_USE_PLATFORM_ macro externally. But yeah you're right, I forgot about this detail as well.

For all platforms except for Linux there's just one VK_USE_PLATFORM_* value that's valid, so CMake could define and export this define externally to ensure consistency. I'm not sure what the right approach for Linux is...

**Comment by zeux** [comment]
Can Linux export *all* possible platforms? I think this makes the extensions available but maybe there's no conflicts between all these?

**Comment by jweg** [comment]
Exporting everything on Linux would mean assuming the existence of Xrandr and wayland-client.h, that won't work. We could make all these things options for CMake (and make those available as install features in vcpkg), but that'd mean those options would have to be kept in sync with the defines used in future versions of vulkan.h, most probably manually; that'd go against the generated nature of volk, I feel.
On the other hand, using the source (e.g. manual copy or git submodule) from one's own project via add_subdirectory, adding to volk's defines as one sees fit, and building it as part of the project is made much worse through my changes, I fear -- if anyone actually did that -- because the outer project now inherits volk as an additional install target all of a sudden.
Much as it pains me to say this, but you should probably revert my changes.

**Comment by zeux** [comment]
This should be addressed by #34 - you can use volk as a CMake dependency and specify extra defines through VOLK_STATIC_DEFINES, or you can use volk_headers instead for a stb-style header config and define VOLK_IMPLEMENTATION in one of the source files. Huge thanks to @jweg for making this happen.
