### ISSUE TITLE
Expose volkGenLoadLoader

### ISSUE THREAD

**Issue by Themaister** [zeux/volk#3]
I have a use-case where I'd like to load my own vulkan.so, and provide my own vkGetInstanceProcAddr to volk. It seems like just making volkGenLoadLoader public would enable that.

**Comment by Themaister** [comment]
That's probably better than the PR I made, feel free to close it.

**Comment by zeux** [comment]
Hmm - would it make more sense to provide something like this?

    void volkInitializeCustom(PFN_vkGetInstanceProcAddr GIPA);

Currently volk only loads GIPA using the platform-specific symbol resolution functions, and loads everything else using GIPA - providing a custom GIPA function seems cleaner in this case. Let me know if this would work for you and I can make this change.

**Comment by Themaister** [comment]
That would map better to what I need, so that looks like an ideal API to me.
