### ISSUE TITLE
VK_KHR_ray_tracing not usable on Windows

### ISSUE THREAD

**Issue by SaschaWillems** [zeux/volk#45]
I can't get the new functions from ```VK_KHR_ray_tracing``` to work via volk. While they are actually included in the volk headers, the function pointers are defined in a new and separate ```vulkan_beta.h``` header file, which doesn't seem to be included by volk at all on Windows.

The main Vulkan header includes that new beta header via a new define:

```cpp
#ifdef VK_ENABLE_BETA_EXTENSIONS
#include "vulkan_beta.h"
#endif
```

But as on Windows, only the Vulkan core headers is explicitly included the beta one isn't included at all.

**Comment by zeux** [comment]
Oops, GH closed this issue :) Can you double-check that it works for you now?

**Comment by SaschaWillems** [comment]
Yes, works fine with that change. Thanks for the quick response :)
