### ISSUE TITLE
PFN_vkGetImageViewAddressNVX undefined

### ISSUE THREAD

**Issue by Harri-Renney** [zeux/volk#48]
Hi!

Cloning the most recent version, PFN_vkGetImageViewAddressNVX appears to be undefined for me. I have Vulkan SDK 1.2.1350 on windows. To work around this, I have commented out all references to PFN_vkGetImageViewAddressNVX and it runs. Maybe i have done something wrong, but incase it's not, thought I'd post this here.

Many thanks

Harri

**Comment by zeux** [comment]
This is a version compat issue :( The NVX extension was changed in 1.2.140, older SDKs expose this extension in the old form. Thanks for reporting, I'll fix this.
