### ISSUE TITLE
Any plan for releases?

### ISSUE THREAD

**Issue by uilianries** [zeux/volk#50]
Hi!

I would like to know if there is any plan for tagging projects versions? 

Regards

**Comment by zeux** [comment]
I can definitely make periodic tagged releases. All changes are versioned in line with Vulkan SDK version; it would make sense to occasionally tag a new one. I can start by tagging the current version :)

**Comment by zeux** [comment]
https://github.com/zeux/volk/releases/tag/1.2.140

**Comment by uilianries** [comment]
Thanks a lot!
