### ISSUE TITLE
volkInitialize() failed

### ISSUE THREAD

**Issue by coldgemini** [zeux/volk#58]
is there any prerequisites before initialize volk?
![image](https://user-images.githubusercontent.com/33364009/100562526-f8a77600-32f6-11eb-95e1-dd5e8e498968.png)

**Comment by zeux** [comment]
> is there any prerequisites before initialize volk?

There aren't. It would be great if you can share the full call stack as well as the module info for vulkan-1.dll (from Modules window in Visual Studio) and the value of `module` here.
