### ISSUE TITLE
Update to Vulkan API 1.1.73 (or 1.1.74) specification version 

### ISSUE THREAD

**Issue by elviras9t** [zeux/volk#6]
Needs to updated version of Volk for newer specification versions of Vulkan API (1.1).

**Comment by zeux** [comment]
Is there a specific entrypoint that you're missing? 1.1.73/74 don't seem to add any new functions, regenerating from the current spec seems to just change VOLK_HEADER_VERSION to 74 without any other changes which is why I haven't updated it.

**Comment by elviras9t** [comment]
Yeah, but version number need for "vulkan.hpp" macro checking.
