### ISSUE TITLE
Missing alias target volk::volk

### ISSUE THREAD

**Issue by loicmouton** [zeux/volk#61]
Hello!
In the CMakeLists.txt, the target volk does not have an alias target volk::volk.

**Comment by zeux** [comment]
PRs are welcome although please be careful with CMake versions since I've just had a complex set of changes that went into one of my other projects, pugixml, around a similar topic - see https://github.com/zeux/pugixml/commits/master/scripts/pugixml-config.cmake.in

**Comment by loicmouton** [comment]
Adding an alias target is available at least since CMake 3.0, which is already the CMake minimum version required by the project. Furthermore, the _volk_headers_ already does have an alias target.

**Comment by zeux** [comment]
Thanks! Yeah ok this is easier, I think the problems I was talking about arise when the package is prepared for distribution but we'll cross that bridge when/if we need to.
