### ISSUE TITLE
Name clash with volk from https://www.libvolk.org/

### ISSUE THREAD

**Issue by daissi** [zeux/volk#66]
Hi,
While working on the Debian package of this volk library, I found there was already an unrelated volk library in Debian (https://www.libvolk.org/). I don't know yet how this could be problematic, but at least the discussion is open.

Best,
Dylan

**Comment by zeux** [comment]
While unfortunate, I don't think there's anything actionable here. If the issue is in package name collision for Debian, I'd recommend using a name like `volk-loader`, assuming the package names can contain dashes.

**Comment by jexposit** [comment]
Hi!

Sorry for commenting in a closed issue, but we are having the same problem in Fedora.

As it doesn't look like renaming this library is an option, I'm considering patching it downstream to avoid conflicts with the volk (GNU Radio) library. Installed files would look like:
https://pagure.io/packaging-committee/issue/1324#comment-889653

It'd be nice if you could provide feedback.

Also, if we could agree on a similar solution for Debian and Fedora we'd avoid software using volk (Vulkan SDK) compiling on Fedora but not compiling on Debian or vice versa.

**Comment by jexposit** [comment]
JFYI, I started the packaging process for Fedora:
https://bugzilla.redhat.com/show_bug.cgi?id=2257275

The package will be available soon. If you find any issues with the package or want to made any change in the future, feel free to ping me and I'll do my best to help you.

**Comment by daissi** [comment]
@jexposit if I understand correctly, so far you are following the Debian way? by just marking both packages in conflicts? you have not applied your patch, right?

I'm all for making things uniform across distros and to avoid the conflict with gnuradio/volk.
