### ISSUE TITLE
Add 1.2.195 tag

### ISSUE THREAD

**Issue by AndreyMlashkin** [zeux/volk#74]
Could you please add tag 1.2.195. I am producing a conan recipe specifically for this version
https://github.com/conan-io/conan-center-index/pull/8049#event-5621014351

I would have volk with the same version as well.
Thanks!

**Comment by AndreyMlashkin** [comment]
@zeux, could you also please add 1.2.198?

**Comment by zeux** [comment]
I can add 198 but 195 doesn't correspond to a specific revision

**Comment by AndreyMlashkin** [comment]
Ok, I see, that's fine

**Comment by zeux** [comment]
I've added 1.2.198
