### ISSUE TITLE
Add option to disable the volk target

### ISSUE THREAD

**Issue by TheMostDiligent** [zeux/volk#78]
At the moment, the `volk` target is always created by CMake. However, when `VOLK_PULL_IN_VULKAN` is `OFF`, the target is not complete and will not build unless path to Vulkan headers is explicitly added. When `VOLK_PULL_IN_VULKAN` is `OFF`, the application most likely only needs the `volk_headers` target and has to explicitly remove `volk` from build.
It would be very helpful if there was an option to only define the `volk_headers` target, e.g. `VOLK_HEADERS_ONLY`

**Comment by zeux** [comment]
Something like VOLK_HEADERS_ONLY would make sense as a CMake option. Feel free to contribute a PR!
