### ISSUE TITLE
Hi from the other VOLK project

### ISSUE THREAD

**Issue by jdemel** [zeux/volk#80]
Hi!

I'm one of the maintainers for the [Vector Optimized Library of Kernels (VOLK)](https://github.com/gnuradio/volk).
I was just made aware of your project and I guess you didn't know about ours.

I can imagine that users who try to install both projects might run into issues. We haven't received any issues though. Feel free to get in touch in case this happens.

**Comment by zeux** [comment]
Yeah this was raised in #66 but it's unclear if this can be problematic as there's no actual symbol name conflict I'd assume, and the domains are a little different. Plus at this point I don't think it's easy to rename either :) Name collisions in package distributions should be easy to resolve if they arise by just picking a suffix.
